update
Iryna-Gry/fix-lab-project pull request #32
Opened 2023-08-03 17:25 UTC by DimaHavr

Додано ще три категорії і відсортовано, як на макеті

2023-08-04 08:24 UTC, Iryna-Gry requested changes
додай будь ласка на секцію кур'єра адаптив на мобільну та таблет версії

2023-08-05 13:13 UTC, DimaHavr commented
додано адаптив на всі екрани;
додано анімацію при ховері на кнопку

2023-08-06 06:36 UTC, Iryna-Gry approved these changes

2023-08-06 06:40 UTC, Iryna-Gry requested changes
Відрефактори код за компонентами. 
Винеси Баттон у окремий компонент там де стилізація загальна, тобто ховер світло-блакитний. 
додай будь ласка цей баттон усюди за своїми секціями та модалками
Текст у баттоні на секції кур'єра "Потрібен кур'єр". Там інше написане

2023-08-06 11:01 UTC, DimaHavr commented
одинакові кнопки винесено в окремі компоненти

2023-08-06 19:20 UTC, Iryna-Gry approved these changes

2023-08-06 19:21 UTC, merged