Feature/body/for business page
Iryna-Gry/fix-lab-project pull request #37
Opened 2023-08-12 09:06 UTC by dmytro-komlyk

1. Created for business section
2. Created call us component
3. Added sx font-size to tailwind

2023-08-12 11:22 UTC, Iryna-Gry requested changes

2023-08-12 11:22 UTC, Iryna-Gry commented on app/(layouts)/(components)/CallUsCard.tsx
передивитися номера телефонів. Вони не мають бути однаковими

2023-08-12 11:22 UTC, Iryna-Gry commented on app/(pages)/corporate/(components)/ForBusinessSection.tsx
передивитися усюди fontFamily. Шрифт усюди Інтер, має бути Інтер та Ексо2. Подивитися як зроблено на сторінці ремонт отримання Головна > Ремонт, зробити так само на для бізнесу

2023-08-12 11:22 UTC, Iryna-Gry commented on app/(pages)/corporate/(components)/GadgetsList.tsx
навіщо тут масив з цифрами? який порядок?

2023-08-12 11:22 UTC, Iryna-Gry commented on tailwind.config.js
Прибери зі змінної лайн хайт. Фонт сайз окремо, лайнхайт окремо. У тейлвінда є клас для лайнхайт коефіцієнта 1.5. Подивися доку

2023-08-12 12:23 UTC, dmytro-komlyk commented on app/(pages)/corporate/(components)/GadgetsList.tsx
Порядок як буде відображатися блок з гаджатами в лептопах як в макеті

2023-08-14 10:16 UTC, Iryna-Gry requested changes
підключи секції нижче за макетом.

2023-08-14 17:22 UTC, Iryna-Gry approved these changes

2023-08-14 17:22 UTC, merged