refactor: moved and changed adress card component, fix styles
Iryna-Gry/fix-lab-project pull request #41
Opened 2023-08-16 11:06 UTC by dmytro-komlyk

2023-08-17 09:06 UTC, Iryna-Gry requested changes

2023-08-17 09:06 UTC, Iryna-Gry commented on app/(layouts)/(components)/AddressLocationCard.tsx
Анімація має працювати тільки на 1440 або треба зменшувати розміри шрифтів, бо на екранах менше верстка приховері ламається

2023-08-17 09:21 UTC, dmytro-komlyk commented on app/(layouts)/(components)/AddressLocationCard.tsx
Верста ламалася через картинку.
![image](https://github.com/Iryna-Gry/fix-lab-project/assets/29660852/c23803d3-c833-4bec-80ca-c7213ffe104e)
 Анімація коли картинка прихована
![image](https://github.com/Iryna-Gry/fix-lab-project/assets/29660852/c82f0ea3-f6dc-48ce-b2cf-555816fd054f)

2023-08-21 15:44 UTC, Iryna-Gry approved these changes

2023-08-21 15:46 UTC, merged