Hero, slider, progress bar, responsive
Iryna-Gry/fix-lab-project pull request #46
Opened 2023-08-16 17:59 UTC by vitalii-zavhorodnii

https://shorturl.at/ghqyO
https://shorturl.at/acekV

2023-08-17 09:58 UTC, Iryna-Gry requested changes

2023-08-17 09:58 UTC, Iryna-Gry commented on app/(components)/HeroSlider/HeroSlider.tsx
На мобільній версії слайдер на 1 картку, має бути 3. Також слайдер виходить за межі сторінки створюючи горизонтальний скролл. Градієнт уплив на 1100 контейнері
![image](https://github.com/Iryna-Gry/fix-lab-project/assets/108401183/b5dce31c-9143-49b2-b1b8-7be060205a2f)

![image](https://github.com/Iryna-Gry/fix-lab-project/assets/108401183/51a745bb-60ed-43b7-9a11-ca0a6cdb6842)
![image](https://github.com/Iryna-Gry/fix-lab-project/assets/108401183/df84c2e7-15fe-43e5-b1d2-200036045e2b)

2023-08-17 09:58 UTC, Iryna-Gry commented on app/(components)/HeroSlider/HeroSlider.tsx
на картках слайдеру немає лінок і ефекту ховера

2023-08-18 09:48 UTC, vitalii-zavhorodnii commented
Вилив правки

2023-08-21 15:56 UTC, Iryna-Gry requested changes

2023-08-21 15:56 UTC, Iryna-Gry commented on app/(layouts)/(components)/HeroSlider/HeroSlider.tsx
Зроби одразу планшетну версію слайдера також притиснутою до лівого боку, як на десктопі. 
![image](https://github.com/Iryna-Gry/fix-lab-project/assets/108401183/d7196a59-a4b8-4b2f-a7e1-0e65c7f35376)
Бо виходить отаке. Це і на планшеті і на моєму лептопі, у якого екран менший за 1440. Зроби будь ласка як на десктопі. притиснутий вліво.
Все інше супер.

2023-08-22 20:14 UTC, vitalii-zavhorodnii commented on app/(layouts)/(components)/HeroSlider/HeroSlider.tsx
Виправив, теперь слайдер починается з 768px

2023-08-29 13:42 UTC, Iryna-Gry approved these changes

2023-08-29 13:43 UTC, merged